/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import * as XLSX from 'xlsx';
import { BaseClienteRow, BaseSkuRow } from './types';

// Robust helper to parse Brazilian locale currency and percentages to raw JS floats.
export function parseExcelNumber(val: any): number {
  if (val === undefined || val === null) return 0;
  if (typeof val === 'number') return val;
  
  const str = String(val).trim();
  if (!str) return 0;
  
  // If it's a percentage (e.g., "22,5%" or "22.5%")
  if (str.endsWith('%')) {
    const numericPart = str.slice(0, -1).trim().replace(/\./g, '').replace(',', '.');
    const parsedPercentage = parseFloat(numericPart);
    return isNaN(parsedPercentage) ? 0 : parsedPercentage / 100;
  }
  
  // Clean currency symbols, white spaces
  let cleaned = str.replace(/[R$\s]/g, '');
  
  // Replace decimal separators for Portuguese/German "1.234,56"
  if (cleaned.includes(',') && cleaned.includes('.')) {
    if (cleaned.indexOf('.') < cleaned.indexOf(',')) {
      // Dot is thousand, comma is decimal
      cleaned = cleaned.replace(/\./g, '').replace(',', '.');
    } else {
      // Comma is thousand, dot is decimal (US)
      cleaned = cleaned.replace(/,/g, '');
    }
  } else if (cleaned.includes(',')) {
    // Only comma exists: assumed decimal
    cleaned = cleaned.replace(',', '.');
  }
  
  const parsed = parseFloat(cleaned);
  return isNaN(parsed) ? 0 : parsed;
}

// Helper to clean Pivot-table expand/collapse glyphs and extra outer/inner spacing
export function cleanPivotString(val: any): string {
  if (val === undefined || val === null) return '';
  const str = String(val);
  // Remove pivot expand/collapse indicators like ⊟, ⊞, indicators • ▪ ▫, and trim outer spacing
  let cleaned = str.replace(/[⊟⊞•▪▫]/g, '');
  cleaned = cleaned.trim();
  // Consolidate any multiple spaces (frequently generated by nested pivot cells in Excel)
  cleaned = cleaned.replace(/\s+/g, ' ');
  return cleaned;
}

// Find a column key in an object by looking for sub-string keywords (case-insensitive)
function getColumnKey(obj: any, keywords: string[]): string {
  const keys = Object.keys(obj);
  for (const key of keys) {
    const lowerKey = key.toLowerCase()
      .replace(/[⊟⊞•▪▫]/g, '')
      .trim()
      .replace(/[\s_/]+/g, ' '); // treat slashes as space dividers too (e.g., "ano/mês" -> "ano mês")
    if (keywords.some(kw => lowerKey.includes(kw.toLowerCase().trim()))) {
      return key;
    }
  }
  return '';
}

export interface ParsedExcelResult {
  clienteRows: BaseClienteRow[];
  skuRows: BaseSkuRow[];
  error?: string;
}

export function parseExcelFile(arrayBuffer: ArrayBuffer): ParsedExcelResult {
  try {
    const data = new Uint8Array(arrayBuffer);
    const workbook = XLSX.read(data, { type: 'array' });
    
    // Find Sheet Names case-insensitively with hierarchical matchers
    let skuSheetName = workbook.SheetNames.find(
      name => {
        const clean = name.toLowerCase().replace(/[\s_-]/g, '');
        return clean.includes('basemargemsku') || clean.includes('margemsku');
      }
    );
    let clienteSheetName = workbook.SheetNames.find(
      name => {
        const clean = name.toLowerCase().replace(/[\s_-]/g, '');
        return clean.includes('basemargemcliente') || clean.includes('margemcliente') || clean.includes('margembasecliente');
      }
    );
    
    // Fallback search to find any sheet containing "sku" or "cliente" / "client"
    if (!skuSheetName) {
      skuSheetName = workbook.SheetNames.find(
        name => {
          const clean = name.toLowerCase();
          return clean.includes('sku') && !clean.includes('cliente') && !clean.includes('client');
        }
      );
    }
    if (!clienteSheetName) {
      clienteSheetName = workbook.SheetNames.find(
        name => {
          const clean = name.toLowerCase();
          return clean.includes('cliente') || clean.includes('client');
        }
      );
    }
    
    if (!skuSheetName && !clienteSheetName) {
      return {
        clienteRows: [],
        skuRows: [],
        error: 'Nenhuma aba correspondente encontrada. Certifique-se de que o arquivo contém as abas "Base Margem SKU" ou "Base Margem Cliente".'
      };
    }
    
    const clienteRows: BaseClienteRow[] = [];
    const skuRows: BaseSkuRow[] = [];
    
    // 1. Process Cliente Sheet if available
    if (clienteSheetName) {
      const sheet = workbook.Sheets[clienteSheetName];
      // Headers start at line 5 (0-indexed row index 4)
      const rawRows = XLSX.utils.sheet_to_json<any>(sheet, { range: 4 });
      
      if (rawRows.length > 0) {
        const sampleRow = rawRows[0];
        
        // Find column keys matching keywords (including robust new matches)
        const keyRef = getColumnKey(sampleRow, ['ano', 'mes', 'mês', 'rotulo', 'linha', 'rotulos', 'mês/ano', 'data', 'date', 'periodo', 'período']);
        const keyRazao = getColumnKey(sampleRow, ['razao', 'social', 'cliente', 'customer', 'distribuidor', 'nome']);
        const keyEstado = getColumnKey(sampleRow, ['estado', 'uf', 'cod_estado', 'state', 'region']);
        const keyGrupo = getColumnKey(sampleRow, ['grupo', 'desc', 'categoria', 'cod desc grupo', 'familia', 'família']);
        const keyProduto = getColumnKey(sampleRow, ['produto', 'sku', 'cod_produto', 'codigo', 'código', 'prod']);
        const keyKardex = getColumnKey(sampleRow, ['kardex', 'custo', 'cost', 'unit', 'soma de kardex unit']);
        const keyDedutores = getColumnKey(sampleRow, ['dedutores', 'dedutor', 'deducoes', 'deduções', 'sem vpx', 'soma de dedutores sem vpx']);
        
        rawRows.forEach((row) => {
          // Safely extract and clean properties
          const rotuloLinha = cleanPivotString(row[keyRef] || row['Rótulos de Linha'] || row['rotuloLinha'] || '');
          const razaoSocial = cleanPivotString(row[keyRazao] || row['Razao_Social'] || row['razaoSocial'] || '');
          const codEstado = cleanPivotString(row[keyEstado] || row['Cod_Estado'] || row['codEstado'] || '').toUpperCase();
          const codDescGrupo = cleanPivotString(row[keyGrupo] || row['Cod Desc Grupo'] || row['codDescGrupo'] || '');
          const codProduto = cleanPivotString(row[keyProduto] || row['cod_produto'] || row['codProduto'] || '');
          
          const rawKardex = row[keyKardex] ?? row['Soma de Kardex unit'] ?? row['kardexUnit'] ?? 0;
          const rawDedutores = row[keyDedutores] ?? row['Soma de Dedutores sem VPX/VPC/cust. fin. stk'] ?? row['dedutores'] ?? 0;
          
          if (rotuloLinha && (razaoSocial || codProduto)) {
            clienteRows.push({
              rotuloLinha,
              razaoSocial,
              codEstado,
              codDescGrupo,
              codProduto,
              kardexUnit: parseExcelNumber(rawKardex),
              dedutores: parseExcelNumber(rawDedutores)
            });
          }
        });
      }
    }
    
    // 2. Process SKU Sheet if available
    if (skuSheetName) {
      const sheet = workbook.Sheets[skuSheetName];
      const rawRows = XLSX.utils.sheet_to_json<any>(sheet, { range: 4 });
      
      if (rawRows.length > 0) {
        const sampleRow = rawRows[0];
        
        const keyRef = getColumnKey(sampleRow, ['ano', 'mes', 'mês', 'rotulo', 'linha', 'rotulos', 'mês/ano', 'data', 'date', 'periodo', 'período']);
        const keyEstado = getColumnKey(sampleRow, ['estado', 'uf', 'cod_estado', 'state', 'region']);
        const keyGrupo = getColumnKey(sampleRow, ['grupo', 'desc', 'categoria', 'cod desc grupo', 'familia', 'família']);
        const keyProduto = getColumnKey(sampleRow, ['produto', 'sku', 'cod_produto', 'codigo', 'código', 'prod']);
        const keyKardex = getColumnKey(sampleRow, ['kardex', 'custo', 'cost', 'unit', 'soma de kardex unit']);
        const keyDedutores = getColumnKey(sampleRow, ['dedutores', 'dedutor', 'deducoes', 'deduções', 'sem vpx', 'soma de dedutores sem vpx']);
        
        rawRows.forEach((row) => {
          const rotuloLinha = cleanPivotString(row[keyRef] || row['Rótulos de Linha'] || '');
          const codEstado = cleanPivotString(row[keyEstado] || row['Cod_Estado'] || '').toUpperCase();
          const codDescGrupo = cleanPivotString(row[keyGrupo] || row['Cod Desc Grupo'] || '');
          const codProduto = cleanPivotString(row[keyProduto] || row['cod_produto'] || '');
          
          const rawKardex = row[keyKardex] ?? row['Soma de Kardex unit'] ?? 0;
          const rawDedutores = row[keyDedutores] ?? row['Soma de Dedutores sem VPX/VPC/cust. fin. stk'] ?? 0;
          
          if (rotuloLinha && codProduto) {
            skuRows.push({
              rotuloLinha,
              codEstado,
              codDescGrupo,
              codProduto,
              kardexUnit: parseExcelNumber(rawKardex),
              dedutores: parseExcelNumber(rawDedutores)
            });
          }
        });
      }
    }
    
    return {
      clienteRows,
      skuRows
    };
  } catch (err: any) {
    return {
      clienteRows: [],
      skuRows: [],
      error: `Erro ao analisar arquivo Excel: ${err.message || err}`
    };
  }
}
